# Generated by Django 5.2.17 on 2026-10-03 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubbing', '0002_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=320, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_running', models.BooleanField(default=True)),
                ('ffmpeg_version', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'dub worker',
                'verbose_name_plural': 'dub workers',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
