# Generated by Django 5.2.17 on 2026-09-25 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_systemsettings_require_email_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short reference, e.g. M3.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("foundation", "Foundations"),
                            ("phase1", "Phase 1 · Dubbing & translation"),
                            ("phase2", "Phase 2 · Live translation"),
                            ("phase3", "Phase 3 · Learn"),
                            ("ongoing", "Ongoing"),
                        ],
                        default="phase1",
                        max_length=12,
                    ),
                ),
                (
                    "goal",
                    models.TextField(
                        blank=True, help_text='What "done" means for this milestone.'
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in the roadmap (lowest first)."
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Set automatically when the last task is ticked.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position within the milestone."
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("data", "Data"),
                            ("models", "Models"),
                            ("operations", "Operations"),
                            ("legal", "Legal & consent"),
                            ("community", "Community"),
                            ("business", "Business"),
                        ],
                        default="platform",
                        max_length=12,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="How to do it, and how to know it worked."
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text='Where to do it or read more, e.g. "ml/DATASETS.md §5" or "Settings → Email".',
                        max_length=200,
                    ),
                ),
                (
                    "command",
                    models.TextField(
                        blank=True,
                        help_text="Command to run, if any. Shown with a copy button.",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, help_text="Who is responsible.", max_length=80
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                (
                    "done_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Results, decisions, links. Kept with the task.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="system.milestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "roadmap task",
                "ordering": ["milestone__order", "order", "pk"],
            },
        ),
    ]
