"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env(name, default=''):
    """Read an environment variable; blank values (common on hosting dashboards) count as unset."""
    value = os.getenv(name, '').strip()
    return value if value else default


def env_list(name, default=''):
    return [item.strip() for item in env(name, default).split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', 'django-insecure-development-only-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# On Vercel, trust the addresses Vercel assigns to this deployment automatically.
for _var in ('VERCEL_URL', 'VERCEL_BRANCH_URL', 'VERCEL_PROJECT_PRODUCTION_URL'):
    _host = env(_var)
    if _host:
        ALLOWED_HOSTS.append(_host)
        CSRF_TRUSTED_ORIGINS.append(f'https://{_host}')
if env('VERCEL'):
    # The production domain, so the site works even before env vars are set.
    for _host in ('ndimi.jeotamedia.co.ke', 'www.ndimi.jeotamedia.co.ke'):
        if _host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_host)
            CSRF_TRUSTED_ORIGINS.append(f'https://{_host}')
    # Never show Django's debug pages on Vercel unless explicitly turned on.
    DEBUG = env('DJANGO_DEBUG', 'false').lower() in ('1', 'true', 'yes', 'on')
    # Vercel terminates HTTPS and forwards the original scheme in this header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'projects',
    'system',
    'dubbing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'system.middleware.MaintenanceModeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'system.context_processors.site_settings',
                'accounts.context_processors.layout',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Set DATABASE_URL (e.g. a Neon or Supabase Postgres URL) in production.
# Without it, a local SQLite file is used for development.
if env('DATABASE_URL'):
    import dj_database_url

    DATABASES = {
        # conn_max_age=0: serverless functions shouldn't hold connections open.
        'default': dj_database_url.parse(env('DATABASE_URL'), conn_max_age=0, ssl_require=True),
    }
    # Neon's pooled URL runs through PgBouncer, which doesn't support server-side cursors.
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # The dub worker and web server write at the same time; wait instead of failing.
            'OPTIONS': {'timeout': 30},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files (demo videos). Served only to signed-in users by
# config.views.protected_media, never publicly.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Starting value only; admins change it in System settings.
MAX_VIDEO_UPLOAD_MB = int(env('MAX_VIDEO_UPLOAD_MB', '500'))

# Email is sent with the SMTP settings admins enter in /admin/ (System management
# > Email settings). Until that is turned on, emails print in the server console.
EMAIL_BACKEND = 'system.email.DatabaseEmailBackend'
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', 'Ndimi <no-reply@localhost>')

# Encrypts SMTP passwords and API keys saved in the database. Generate one with:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Keep it safe: if it changes, saved secrets must be entered again.
FIELD_ENCRYPTION_KEY = env('FIELD_ENCRYPTION_KEY')

# Authentication and access rights
# Access is permission-based. Admins build groups in /admin/ > Groups and tick
# the permissions each group gets. "Staff status" lets a user open /admin/;
# what they can see and change there comes from their permissions.
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MongoDB stores application documents; Django's SQLite database stores
# built-in admin, auth, and session data until a relational database is added.
MONGO_URI = env('MONGO_URI', 'mongodb://127.0.0.1:27017')
MONGO_DB_NAME = env('MONGO_DB_NAME', 'sauti_yetu')
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:5500')
